#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/elementary/.local/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/elementary/.local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/elementary/Documents/Praktikum/Simulations/WORKSPACE_T2N/Tutorials/lib_mech/x86_64/.libs/libnrnmech.so" "$@"
